### ISSUE TITLE
ruby: while loops/blocks not recognized

### ISSUE THREAD

**Issue by ccaroon** [HTD/NST#14]
The Ruby parser does not increment the depth for 'while' loops, which causes the indention to be off for method names after a 'while' loop appears in the code.

Here's  a patch:

```
1204c1204
<         else if ( code.match(/^(if|unless|case)\b/) ) {

---
>         else if ( code.match(/^(if|unless|case|while)\b/) ) {
```

**Comment by jumpercc** [comment]
wrong highlighted code:

``` ruby
class One
  def foo
    while true
      puts "hello!"
    end
  end

  def bar
    i = 0
    begin
      i +=1
    end while i < 5
  end

  def baz
    i = 0
    begin
      i = 10
    end if false
  end

  def quux
    # here
  end
end
```

"foo", "bar", "baz" and "quux" must be on the same level

**Comment by jumpercc** [comment]
fixed in "testing"
$ git push
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 494 bytes, done.
Total 4 (delta 2), reused 0 (delta 0)
To git@github.com:HTD/NST.git
   8b4df59..c4240da  testing -> testing
