### ISSUE TITLE
Severe lag on Komodo Edit 8.5

### ISSUE THREAD

**Issue by brianjcohen** [HTD/NST#34]
Yesterday I let Komodo Edit auto-update to 8.5.  Upon restart, I am finding that the entire Komodo Edit UI is laggy as long as NST ("Source") is selected in the right-hand sidebar.  If I have the "Toolbox" selected, everything (eg. scrolling, typing, menu interaction) is snappy. But if I switch to NST ("Source"), there is severe lag while attempting any of those actions, so long as I'm also currently looking at a PHP file in the editor pane.

This is on Ubuntu, 64-bit.

**Comment by brianjcohen** [comment]
I closed this issue because I believe I've confirmed this has nothing to do with NST, and is in fact an issue with Komodo Edit 8.5. The lag exists regardless of NST being enabled, and is resolved by downgrading to Komodo Edit 8.0.2.

**Comment by drener** [comment]
For me the lag goes away a few seconds after I disable the NST sidebar with 8.5, and it doesn't show up with other sidebars open so it seems like something changed with sidebar handling in 8.5, and/or there is indeed a problem with NST.

**Comment by brianjcohen** [comment]
drener, I initially thought this was the case as well, until I completely removed NST and restarted Komodo and found the lag still existed.

**Comment by brianjcohen** [comment]
Looks like this is resolved as of the 0.62 version available here on Github.
