### ISSUE TITLE
Display Bug Chops off NST objects

### ISSUE THREAD

**Issue by rsyring** [HTD/NST#4]
I just wanted to bring back to your attention a bug report I made in the Active State comments.

In the source tree window, the objects in the tree are cut off about 40% too early. Its almost like NST thinks the window is much more narrow than it actually is.

This only happens in the NST window in my primary editor instance. If I open a new editor window, the NST display is correct there, that is, the elements span the entire width of the NST window. 

Screenshots:

http://rcs-comp.com/tmp/nst1.png
http://rcs-comp.com/tmp/nst2.png
http://rcs-comp.com/tmp/nst3.png
http://rcs-comp.com/tmp/nst4.png

You have said you are not able to reproduce this.  Its something I can't STOP reproducing :).  I have a fresh install of Xubuntu  11.10, fresh install of Komodo Edit, and fresh install of NST.  

If you are not able to reproduce, I'd be happy to setup a VM on one of our servers with the problem so you can troubleshoot.

Thanks.

**Comment by HTD** [comment]
Fixed? :) Ok, time for 7.x compatibility... Today or next week, so wish me luck.

**Comment by rsyring** [comment]
Yes, its fixed, thanks!
