### ISSUE TITLE
Komodo Edit 9 Support

### ISSUE THREAD

**Issue by pixxelfactory** [HTD/NST#47]
This is more a feature-request than bug.
It is not compatible with the latest version of Komodo Edit.
Are there any plans to make it work with that?

Best regards and thanks for this exceptional plugin!

**Comment by torstenberg** [comment]
There is already a fix for this, it has just not been merged into the code yet. See here:

https://github.com/HTD/NST/pull/45

You can just do this in your local copy, then you do not need to wait until someone updates the code here on github. Just edit the file install.rdf and change the line

em:maxVersion8.*/em:maxVersion

to

em:maxVersion9.*/em:maxVersion

and reinstall the plugin. Then it works.

**Comment by pixxelfactory** [comment]
Thanks, this works!
