### ISSUE TITLE
Javascript: Node.js / Express.js support

### ISSUE THREAD

**Issue by remoe** [HTD/NST#5]
Hi

First, thanks for this nice plugin ;)

For example in Node.js / Express.js (http://expressjs.com/guide.html) it is usual to write following:

app.get('/url1', function(req, res)
{
});

app.get('/url2', function(req, res)
{
});

app.post('/mypost', function(req, res)
{
});

Is it possible to list such constructs in the NST as for example get(url1), get(url2), post(mypost) ?

Thanks

**Comment by HTD** [comment]
I tried to do something about it yesterday, but I failed.
Simple changes in function definition regex won't be enough.
Regex rewriting function must be modified.

Feel free to try this on your own and post your changes
on github if you succeed.

I will add Node.js support anyway, so if you wait for
a week or two it will be there one way or another.

I recently added Komodo 7 support. I haven't committed
my latest changes yet, and some minor bugs are fixed.

In v0.60 parsers and tree widget will be separated.
I plan to add a simple debugger too.

For now, you can try to use different syntax, like:

RequestActions = {
    MyAction1 : function(req, res) {
    },
    MyAction2 : function(req, res) {
    }
};

app.get('/url1', RequestActions.MyAction1);
app.get('/url2', RequestActions.MyAction2);

It seems even a little more readable :)
All URLs together, and all handlers nicely
separated.

Be aware, when we start showing all anonymous
functions in source tree - it can grow really
large (and when it's too large, it's again
hard to find anything).

Cheers,
A.

On Tue, 24 Jan 2012 20:24:12 +0100, Remo E  
reply@reply.github.com  
wrote:

> Hi
> 
> In Node.js / Express.js (http://expressjs.com/guide.html) it is usual to  
> write following:
> 
> app.get('/url1', function(req, res)
> {
> });
> 
> app.get('/url2', function(req, res)
> {
> });
> 
> app.post('/mypost', function(req, res)
> {
> });
> 
> Is it possible to list such constructs in the NST as for example  
> get(url1), get(url2), post(mypost) ?
> 
> Thanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HTD/NST/issues/5

## 

Using Opera's revolutionary email client: http://www.opera.com/mail/

**Comment by remoe** [comment]
Thanks for help ;) I'm looking forward to the new version.

Remo
