### ISSUE TITLE
wrong nesting for perl functions inside module

### ISSUE THREAD

**Issue by jumpercc** [HTD/NST#6]
Wrong nesting for perl functions inside module.
For following code function "one" in NST nested inside module "Foo", but function "two" outside (must be inside)

```
package Foo;

sub one {
    if ( $#_ ) {
        1;
    }
}

sub two {
    1;
}

1;
```

screenshot:
http://files.codejumper.ru/nst-bug.png

Komodo Edit, version 7.0.2, build 9923, platform linux-x86
NST 0.59

**Comment by HTD** [comment]
Confirmed. Scheduled for weekend.

**Comment by jumpercc** [comment]
Thank you

**Comment by HTD** [comment]
Fixed in current testing branch.

**Comment by jumpercc** [comment]
the same for

```
package Test;

sub foo {
    $_ =~ s{#}{\%23}g;
}

sub bar {
    #
}

1;
```

i think it can be done in issue #7
