### ISSUE TITLE
perl: searching for subs inside quoted text, pod, after __END__

### ISSUE THREAD

**Issue by jumpercc** [HTD/NST#7]
perl: searching for subs inside quoted text, pod, after __END__

In the following code "not_a_subX" are just quoted strings/documentation/data.
But NST shows it in source tree as subroutimes.

```
package Foo;

print q{sub not_a_sub};

print qq{sub not_a_sub2};

print <<'END_TEXT';
sub not_a_sub3
END_TEXT

=pod
sub not_a_sub4
=cut

m{sub not_a_sub5};

1;

__END__

sub not_a_sub6
```

screenshot:
http://files.codejumper.ru/nst-bug2.png

In real code this issue affects perl files with documentation and/or code for generating code.

There is more exotic ways, but them don't used in real code:

```
print q~sub not_a_sub~;
```

**Comment by jumpercc** [comment]
Komodo Edit, version 7.0.2, build 9923, platform linux-x86
NST 0.59

**Comment by HTD** [comment]
This one is a little bit harder to fix. I have no time to do it right now, maybe next week. It's quite a challenge, because we miss some block literals rules here. It should be done similar to Python's block literals, but we need advanced opening and closing sequence matching. Maybe you give it a try? :) Preprocessor class is the one which takes care of literals and comments. Anything you change, be sure not to break compatibility with other language definitions. And it would be nice if the rules would be somehow passed to Preprocessor instance.

**Comment by jumpercc** [comment]
ok, i'll try to do it

**Comment by jumpercc** [comment]
and another one
packages nested, but it's wrong - must be with the same level
screenshot: http://files.codejumper.ru/nst-bug-packages.png

```
package Foo;
sub foo { 1 }
1;

package Bar;
sub bar { 1 }
1;

package Baz;
sub baz { 1 }
1;
```

**Comment by jumpercc** [comment]
+1 to future me:
wrong nesting for subroutines declarations
screenshot: http://files.codejumper.ru/nst-bug-sub-declarations.png

```
# subroutines declarations
sub ConfigDefaults();
sub ParseOptionSpec($$);
sub OptCtl($);
sub FindOption($$$$$);
sub ValidValue ($$$$$);
```

**Comment by jumpercc** [comment]
I've just written fast enough Perl parser (previous version of my Perl parser was precise but too slow).
There is no such bugs in it.
After some extended testing i'll "git push" my changes.

PS: and after a while i'll "git push" my Ruby parser (after extended testing)

**Comment by jumpercc** [comment]
Hello,

I've tried to push my changes, but got this: "ERROR: Permission to HTD/NST.git denied to jumpercc."
( https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user )

How can I submit my changes (bugfix with improved perl parser + ruby parser)?

**Comment by HTD** [comment]
I've just added you as a collaborator, you could try to submit your changes now. Let me know if it works.

**Comment by HTD** [comment]
I think I've fixed it. Try now and let me know.

On Wed, 12 Dec 2012 18:49:48 +0100, jumpercc notifications@github.com  
wrote:

> Hello,
> 
> I've tried to push my changes, but got this: "ERROR: Permission to  
> HTD/NST.git denied to jumpercc."
> (  
> https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user  
> )
> 
> How can I submit my changes (bugfix with improved perl parser + ruby  
> parser)?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HTD/NST/issues/7#issuecomment-11299865

## 

Using Opera's revolutionary email client: http://www.opera.com/mail/

**Comment by jumpercc** [comment]
It works! Thank you.

$ git push
Counting objects: 7, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 4.62 KiB, done.
Total 4 (delta 2), reused 0 (delta 0)
To git@github.com:HTD/NST.git
   868355c..864f99c  testing -> testing
